[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Firebase Configuration - Set these in Netlify dashboard environment variables
  # Never commit actual API keys to version control
  # Use the Web API key from Firebase Console: AIzaSyDPHHj48jXDTeCS_uuZLD0JombGpzyJk_0
  
  # Configure secrets scanning to ignore Firebase configuration values
  # These are public configuration values, not secret keys
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_MEASUREMENT_ID"
